apiVersion: apps/v1
kind: Deployment
metadata:
  name: rocketmq-namesrv
  namespace: rocketmq
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rocketmq-namesrv
  template:
    metadata:
      labels:
        app: rocketmq-namesrv
      annotations:
        sidecar.istio.io/inject: "true"
    spec:
      containers:
      - name: rocketmq-namesrv
        image: apache/rocketmq:5.1.4
        command: ["sh", "-c", "/home/rocketmq/rocketmq-5.1.4/bin/mqnamesrv"]
        env:
        - name: JAVA_OPT_EXT
          value: "-server -Xms512m -Xmx512m"
        - name: NAMESRV_MEM
          value: "-Xms512m -Xmx512m"
        - name: TZ
          value: "Asia/Taipei"
        ports:
        - containerPort: 9876
        volumeMounts:
        - name: namesrv-logs
          mountPath: /home/rocketmq/logs
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"
      volumes:
      - name: namesrv-logs
        emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: rocketmq-namesrv
  namespace: rocketmq
spec:
  ports:
  - port: 9876
    targetPort: 9876
    protocol: TCP
  selector:
    app: rocketmq-namesrv 