apiVersion: apps/v1
kind: Deployment
metadata:
  name: rocketmq-broker
  namespace: rocketmq
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rocketmq-broker
  template:
    metadata:
      labels:
        app: rocketmq-broker
      annotations:
        sidecar.istio.io/inject: "true"
    spec:
      containers:
      - name: rocketmq-broker
        image: apache/rocketmq:5.1.4
        command: ["sh", "-c", "/home/rocketmq/rocketmq-5.1.4/bin/mqbroker -n rocketmq-namesrv.rocketmq.svc.cluster.local:9876 -c /etc/rocketmq/broker.conf"]
        env:
        - name: JAVA_OPT_EXT
          value: "-server -Xms1g -Xmx1g"
        - name: BROKER_MEM
          value: "-Xms1g -Xmx1g"
        - name: TZ
          value: "Asia/Taipei"
        ports:
        - containerPort: 10909  # Broker 通訊端口
        - containerPort: 10911  # Broker 遠程端口
        volumeMounts:
        - name: broker-config
          mountPath: /etc/rocketmq/broker.conf
          subPath: broker.conf
        - name: broker-logs
          mountPath: /home/rocketmq/logs
        - name: broker-store
          mountPath: /home/rocketmq/store
        resources:
          requests:
            memory: "1Gi"
            cpu: "500m"
          limits:
            memory: "2Gi"
            cpu: "1000m"
      volumes:
      - name: broker-config
        configMap:
          name: rocketmq-config
      - name: broker-logs
        emptyDir: {}
      - name: broker-store
        emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: rocketmq-broker
  namespace: rocketmq
spec:
  ports:
  - port: 10909
    targetPort: 10909
    protocol: TCP
    name: broker-port
  - port: 10911
    targetPort: 10911
    protocol: TCP
    name: remote-port
  selector:
    app: rocketmq-broker 